name: David Hutchison
description: I like to develop things. This is my profile.
url: https://about.devwithimagination.com


location: Scotland

highlighter: rouge
markdown: kramdown
timezone: Europe/London
permalink: /:year/:month/:day/:title/
relative_permalinks: false

plugins:
- jekyll-seo-tag
- jekyll-sitemap

excerpt_separator: <!--more-->

exclude: [node_modules]

sass:
  style: compressed