name: David Hutchison
description: I like to develop things. This is my profile.
url: http://www.davidhutchison.scot


location: Scotland

highlighter: rouge
markdown: kramdown
timezone: Europe/London
permalink: /:year/:month/:day/:title/
relative_permalinks: false

plugins:
- jekyll-seo-tag

excerpt_separator: <!--more-->

exclude: [node_modules]

sass:
  style: compressed